name: P E K K O S
url: http://www.pekkos.com
exclude: [
  "styleguide",
  "gruntfile.js",
  "grunt",
  "gulpfile.js",
  "gulp"
  "package.json",
  "node_modules",
  "DONE.md",
  "CNAME",
  "Gemfile",
  "Gemfile.lock",
  "npm-debug.log",
  "README.md",
  "stylelint-readme.md",
  "ui-test",
  ".editorconfig",
  ".browserslistrc",
  ".stylelintrc",
  "fractal.js",
  "stylelint-report.txt"
  ]
permalink: /:categories/:title/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
