name: P E K K O S
url: http://www.pekkos.com
exclude: [
  "patterns",
  "gruntfile.js",
  "package.json",
  "node_modules",
  "DONE.md",
  "CNAME",
  "Gemfile",
  "Gemfile.lock",
  "npm-debug.log",
  "README.md",
  "stylelint-readme.md",
  "ui-test"
  ]
permalink: /:categories/:title/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
